name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-web-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run web and API tests
      run: mvn clean test -Dcucumber.filter.tags="not @desktop and not @mobile"
    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results-web-api
        path: allure-results/

  test-mobile-desktop:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'mobile-desktop') || github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up Appium
      run: |
        npm install -g appium
        appium driver install uiautomator2
        appium driver install xcuitest
    - name: Run mobile and desktop tests
      run: mvn test -Dcucumber.filter.tags="@mobile or @desktop"
    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results-mobile-desktop
        path: allure-results/
